### ISSUE TITLE
PWA Setup Part 1

### ISSUE THREAD

**Issue by chaoranxie** [chaoranxie/cwm#23]
Resources 
[Progressive Web Apps using the Angular Service Worker
](https://docs.google.com/document/d/1F0e0ROaZUnTFftmC0XovpREHWHjcXa4CggiFlmifjhw/edit#heading=h.ekc45bwgdwdw)[Slides](http://slides.com/webmax/pwa-graz#/)

[Great Progressive Web App Experiences with Angular (Google I/O '17)](https://www.youtube.com/watch?v=C8KcW1Nj3Mw&feature=youtu.be&t=681)
[ sw-precache and workbox different tools are all mean to generate service worker for your app
](https://youtu.be/C8KcW1Nj3Mw?t=1112)
[ need to wait for all the app is loaded before loading service worker
](https://youtu.be/C8KcW1Nj3Mw?t=1238)
- [x] experiment with a brand new project
  - [x] check the network tab for before and after, 
  - [x] check the files generated using git

- [x] 9:00am Setting up the environment, setting the goal
- [x] 9:30am Introducing PWA concept (slides)
- [x] 10:30am Step 1 - Initializing Angular Service Worker
- [x] 11:00am Step 2  - Static Content Cache plugin
- [x] 11:30am Step 3 - Route Redirection plugin
- [x] 12:00pm Lunch
- [x] 1:00pm Step 4 - Web App Manifest
- [x] 1:30pm Step 5 - External Content Cache plugin

**Comment by chaoranxie** [comment]
Questions:

- [x] How is the final service worker file looks like?
depends on what service worker file we use, btw default there is `node_modules/@angular/service-worker/bundles/worker-basic.js` that will be copied to the dist folder, but sometime we might generate a file like `https://github.com/webmaxru/pwa-workshop-angular/blob/step9/src/service-worker/rollup.js#L18`
 

- [x] how does browser know which file to load? 
the build process create `sw-register.b73048fe3d9f8a1e7ae5.bundle.js` file and injected to the index.html.

if i add caching for firebase, how does angularfire get new updates? 

How does routing works? what is it use for in the ngsw manifest file

all these app shell setup seems to have gone away

**Comment by chaoranxie** [comment]
it seems like all of these tools are trying to reach the same end goal, in this case it is the service worker config

**Comment by chaoranxie** [comment]
- [x] - Generate service worker 
   - [x] one way is via build step as shown in the good io video
   - [x] another way is integrate with the angular cli, service worker true. 
- [x] - Register service worker

**Comment by chaoranxie** [comment]
at the moment i cant get the server to reload
