### ISSUE TITLE
Scaffolding Epic Story

### ISSUE THREAD

**Issue by chaoranxie** [chaoranxie/cwm#8]
Plunker
https://plnkr.co/edit/A4P4IWpqdi8vdAoEKPmC?p=preview
Angular4
AngularMaterial

Git
- [ ] lint commit hook

Firebase
- [x] Intitialize
- [x] database.rules.json

Travis CI
- [x] deploy script

PWA
- [ ] Service Worker
- [x] Manifest.json
  - [x] icons
- [ ] ngsw-manifest.json

Layout
- [ ] Toolbar
- [ ] Menus
